### ISSUE TITLE
But...how to use it?

### ISSUE THREAD

**Issue by junglized** [fundamentei/organize-css#1]
Hi,

I'm looking for an VSCode extention which'll help me to organize my CSS. I've found this one but.. there is no explanation on how to use it?

Thanks!

**Comment by andreyvital** [comment]
@junglized sorry I missed your issue for that long. Wasn't checking here.

So...you'll select your CSS-in-js object and then run the "organize css" from the command palette. I have all that bound to a hotkey so it's more easier.

```JSON
{
  "key": "cmd+shift+c",
  "command": "extension.organizeCSS",
  "when": "editorTextFocus"
}
```

And also to make easier the selection, I use this extension: https://marketplace.visualstudio.com/items?itemName=letrieu.expand-region

Here's a gif showing how it works:

![Kapture 2020-08-26 at 10 09 45](https://user-images.githubusercontent.com/967317/91307411-4a82b200-e784-11ea-81bf-bfa8b38cd5e8.gif)

**Comment by junglized** [comment]
@andreyvital Your advice was very useful, thank you!

**Comment by andreyvital** [comment]
@junglized thanks, let me know if you have any questions!
